### ISSUE TITLE
Received Job / Solved Job Issue

### ISSUE THREAD

**Issue by develth** [notgiven688/webminerpool#56]
Hi there,

it seems like the output from sendStack when a job is solved (identifier: solved) is always the last "received" jobId with identifier "job".

Sometimes i get two logs from sendStack with identifier solved with the same jobId. 

Is this is known issue?
Thanks

**Comment by develth** [comment]
![example](https://user-images.githubusercontent.com/3374563/41242803-c5e69304-6da0-11e8-836c-c7f645418848.png)
Feel free to check my Screenshot from my console output

**Comment by notgiven688** [comment]
That is all correct. A job can have multiple solutions and can therefore be solved in multiple ways. The miner always works on the latest job it got.

**Comment by develth** [comment]
Thanks for the Information - but why the other jobs wont get "solved"?

**Comment by notgiven688** [comment]
They could not be solved in time. But this is perfectly normal. It all makes sense if you understand the concept of mining (and the ideas of pools). I am sure there are some good articles out there.

**Comment by develth** [comment]
Thanks. 
Is it possible to get to know in the frontend when the job is not solved in time?

**Comment by notgiven688** [comment]
It is not a very useful information (?). If your hashrate is low the pool sees that you are struggeling and sends easier jobs which can be solved faster/easier - you will be rewarded with less shares for each solved job, of course. If you want you can calculate all kind of metrics but the hashrate is the most important.

**Comment by develth** [comment]
I want to save those informations for a stastic reason (how many jobs a client runs and what are solved in e.g. wich time - so i wanted to build a association with jobid & sovled result data). 

Is it possible to get to know how many hashes a client calculated for a solved job?

**Comment by notgiven688** [comment]
The server keeps track of how much work was done by the client, Use startMining(pool, address, password, numThreads, userid); with a userid which is not empty. See the other folder in the SDK to find out how to request that stats.

**Comment by develth** [comment]
Great - thanks for your support.
